title: "Charlotte Manser"
description: "Personal homepage"
remote_theme: remote_theme: "mmistakes/minimal-mistakes@4.27.3"
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
